-- Generated by nwg-displays on 2026-07-12 at 17:30:04. Do not edit manually.

hl.monitor({
    output = "desc:ASUSTek COMPUTER INC XG27AQWMG W3LMTR017821",
    mode = "2560x1440@120.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
